FROM golang:1.23-alpine as builder
LABEL authors="maxpoltoratsky"

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . ./
RUN GOOS=linux GOARCH=amd64 GO111MODULE=on CGO_ENABLED=0 \
    go build -o app ./cmd/client/main.go

FROM alpine:3.20

COPY --from=builder /src /src

ENTRYPOINT ["/src/app"]
